from datetime import datetime, timedelta
from models.user_models import Task

def parse_time_string(time_str):
    """Helper to parse time like '08:00' to today's date with that time"""
    # This is a simplification. Real implementation would handle dates properly.
    try:
        now = datetime.now()
        hour, minute = map(int, time_str.split(':'))
        return now.replace(hour=hour, minute=minute, second=0, microsecond=0)
    except:
        return datetime.now()

def generate_tasks(care_plan):
    """
    Generate a list of Task dictionaries from a Care Plan.
    """
    tasks = []
    patient_id = care_plan['patient_id']
    plan_id = care_plan['plan_id']
    
    # helper to create task dict
    def create_task_dict(type, description, time_obj, priority='normal'):
        return Task.create({
            'task_id': '', # Will be generated by DB
            'patient_id': patient_id,
            'plan_id': plan_id,
            'task_type': type,
            'description': description,
            'scheduled_time': time_obj.isoformat(),
            'priority': priority
        })

    # 1. Medications
    for med in care_plan.get('medications', []):
        med_name = med.get('name', '').strip()
        if not med_name: continue
        
        dose = med.get('dose', '')
        # Frontend provides 'time' (single string) and 'frequency'
        t_str = med.get('time', '09:00')
        freq = med.get('frequency', 'once')
        
        times_to_schedule = []
        base_time = parse_time_string(t_str)
        
        if freq == 'once':
            times_to_schedule.append(base_time)
        elif freq == 'twice': # +12h
             times_to_schedule.append(base_time)
             times_to_schedule.append(base_time + timedelta(hours=12))
        elif freq == 'thrice': # +8h, +16h
             times_to_schedule.append(base_time)
             times_to_schedule.append(base_time + timedelta(hours=8))
             times_to_schedule.append(base_time + timedelta(hours=16))
        elif freq == '4hours':
             for i in range(0, 24, 4):
                 times_to_schedule.append(base_time.replace(hour=0, minute=0) + timedelta(hours=i))
        elif freq == '6hours':
             for i in range(0, 24, 6):
                 times_to_schedule.append(base_time.replace(hour=0, minute=0) + timedelta(hours=i))
        else:
             times_to_schedule.append(base_time)

        for t_obj in times_to_schedule:
            # Ensure time is not in past if care plan started today? 
            # For simplicity, just add them locally
            tasks.append(create_task_dict(
                'medication', 
                f"Give {med_name} ({dose})", 
                t_obj, 
                priority='high'
            ))

    # 2. Meals
    meals = care_plan.get('meals', {})
    if meals.get('morning'):
        t = meals.get('morning_time', '08:00')
        tasks.append(create_task_dict('meal', f"Breakfast: {meals['morning']}", parse_time_string(t)))
    if meals.get('afternoon'):
        t = meals.get('afternoon_time', '13:00')
        tasks.append(create_task_dict('meal', f"Lunch: {meals['afternoon']}", parse_time_string(t)))
    if meals.get('night'):
        t = meals.get('night_time', '19:00')
        tasks.append(create_task_dict('meal', f"Dinner: {meals['night']}", parse_time_string(t)))

    # 3. Vitals
    for vital in care_plan.get('vitals', []):
        name = vital.get('name', '').strip()
        if not name or name == 'Check Vitals': # 'Check Vitals' is default but let's allow custom names only if useful? No, keep default if provided.
             name = vital.get('name', 'Check Vitals')
        
        times = vital.get('times', ['10:00'])
        for t_str in times:
             tasks.append(create_task_dict('vital', name, parse_time_string(t_str), priority='medium'))

    # 4. Bathing/Hygiene
    bathing = care_plan.get('bathing', {})
    if bathing.get('time'):
         tasks.append(create_task_dict('procedure', 'Bathing & Hygiene', parse_time_string(bathing['time'])))

    # 5. Procedures/Injections
    for proc in care_plan.get('procedures', []):
        if not proc.get('name', '').strip(): continue
        tasks.append(create_task_dict('procedure', proc['name'], parse_time_string(proc.get('scheduled_time', '11:00')), priority='high'))
        
    for inj in care_plan.get('injections', []):
         if not inj.get('name', '').strip(): continue
         tasks.append(create_task_dict('procedure', f"Injection: {inj['name']}", parse_time_string(inj.get('time', '12:00')), priority='high'))

    return tasks
